// Auto-generated by deploy.sh
const awsConfig = {
  userPoolId: 'us-east-1_1qRRFJgsD',
  userPoolClientId: '2qiacpso45vgqg6u4f4qidbk76',
  apiEndpoint: 'https://1bi9po5fr1.execute-api.us-east-1.amazonaws.com/',
  region: 'us-east-1',
}
export default awsConfig
