// This file is auto-generated by the deploy script
// Do not edit manually

const awsConfig = {
  userPoolId: import.meta.env.VITE_USER_POOL_ID || '',
  userPoolClientId: import.meta.env.VITE_USER_POOL_CLIENT_ID || '',
  apiEndpoint: import.meta.env.VITE_API_ENDPOINT || '',
  region: 'us-east-1',
}

export default awsConfig
