#!/bin/bash
set -euo pipefail

echo "==> Building frontend..."
cd frontend
npm ci
npm run build
cd ..

echo "==> Installing CDK dependencies..."
pip install -r requirements.txt -q

echo "==> CDK Bootstrap..."
cdk bootstrap --require-approval never 2>/dev/null || true

echo "==> CDK Deploy..."
cdk deploy --require-approval never --outputs-file cdk-outputs.json

echo "==> Parsing CDK outputs..."
STACK_NAME="HealthTrackerStack"
CF_URL=$(python3 -c "import json; d=json.load(open('cdk-outputs.json')); print(d['$STACK_NAME']['CloudFrontURL'])")
USER_POOL_ID=$(python3 -c "import json; d=json.load(open('cdk-outputs.json')); print(d['$STACK_NAME']['UserPoolId'])")
USER_POOL_CLIENT_ID=$(python3 -c "import json; d=json.load(open('cdk-outputs.json')); print(d['$STACK_NAME']['UserPoolClientId'])")
API_ENDPOINT=$(python3 -c "import json; d=json.load(open('cdk-outputs.json')); print(d['$STACK_NAME']['ApiEndpoint'])")
TABLE_NAME=$(python3 -c "import json; d=json.load(open('cdk-outputs.json')); print(d['$STACK_NAME']['TableName'])")
FRONTEND_BUCKET=$(python3 -c "import json; d=json.load(open('cdk-outputs.json')); print(d['$STACK_NAME']['FrontendBucketName'])")
DIST_ID=$(python3 -c "import json; d=json.load(open('cdk-outputs.json')); print(d['$STACK_NAME']['DistributionId'])")

echo "==> Generating frontend config..."
cat > frontend/src/aws-exports.ts << EOF
// Auto-generated by deploy.sh
const awsConfig = {
  userPoolId: '${USER_POOL_ID}',
  userPoolClientId: '${USER_POOL_CLIENT_ID}',
  apiEndpoint: '${API_ENDPOINT}',
  region: 'us-east-1',
}
export default awsConfig
EOF

echo "==> Rebuilding frontend with config..."
cd frontend
npm run build
cd ..

echo "==> Syncing frontend to S3..."
aws s3 sync frontend/dist/ "s3://${FRONTEND_BUCKET}/" --delete

echo "==> Invalidating CloudFront cache..."
aws cloudfront create-invalidation --distribution-id "${DIST_ID}" --paths "/*"

echo "==> Seeding mock data..."
TABLE_NAME="${TABLE_NAME}" python3 scripts/seed_mock_data.py "${TABLE_NAME}"

echo ""
echo "====================================="
echo "Deployment complete!"
echo "CloudFront URL: ${CF_URL}"
echo "====================================="
